package com.bettertrades.db;

import com.bettertrades.BetterTrades;

import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 * When MariaDB comes back, whatever was written in fallback is handed over to it.
 *
 * It is safe to repeat for two reasons: primary keys are generated by the mod (no collisions
 * between the two backends) and the inserts are INSERT IGNORE, so a row that already arrived is
 * not duplicated. The rows stay on SQLite as well: only the queue is cleared.
 */
public final class Replay {

    private record Pending(String kind, String entityId) {}

    private Replay() {}

    public static void schedule(Path sqliteFile) {
        if (sqliteFile == null || Files.notExists(sqliteFile)) return;
        Database.execute(target -> run(sqliteFile, target));
    }

    private static void run(Path sqliteFile, Connection target) throws SQLException {
        if (Database.backend() != Database.Backend.MARIADB) return;

        try (Connection source = DriverManager.getConnection("jdbc:sqlite:" + sqliteFile)) {
            List<Pending> pending = pending(source);
            if (pending.isEmpty()) return;

            BetterTrades.LOGGER.info("Replay towards MariaDB: {} entries queued", pending.size());
            int done = 0;
            for (Pending entry : pending) {
                try {
                    switch (entry.kind()) {
                        case "TRADE" -> replayTrade(source, target, entry.entityId());
                        case "BLACKLIST_ITEM" -> replayBlacklistItem(source, target, entry.entityId());
                        case "BLACKLIST_POKEMON" -> replayBlacklistPokemon(source, target, entry.entityId());
                        case "API_CLIENT" -> copy(source, target, "api_client", "modid = ?", entry.entityId());
                        default -> {
                            // A kind this version does not know comes from a newer one that wrote to
                            // the same file. Dropping it from the queue would lose it forever, and the
                            // final count would call it transferred: it stays where it is.
                            BetterTrades.LOGGER.warn("Unknown kind in replay_pending, left queued: {}",
                                    entry.kind());
                            continue;
                        }
                    }
                    // Commit before forget, not after: Database wraps the whole Work in one
                    // transaction, and without this the entry would leave the queue on SQLite while
                    // the copy on MariaDB is still uncommitted. A rollback at the end would lose
                    // them all without having transferred a single one.
                    target.commit();
                    forget(source, entry);
                    done++;
                } catch (SQLException e) {
                    // The rows this entry had already inserted are still in the open transaction:
                    // without the rollback the NEXT entry's commit would publish them, and MariaDB
                    // would show half a trade - no items, or no Pokemon - for as long as this entry
                    // keeps failing. A failed statement does not end the transaction on its own there.
                    try {
                        target.rollback();
                    } catch (SQLException rollback) {
                        BetterTrades.LOGGER.warn("Replay rollback failed: {}", rollback.getMessage());
                    }
                    BetterTrades.LOGGER.error("Replay of {} {} failed: left queued",
                            entry.kind(), entry.entityId(), e);
                }
            }
            BetterTrades.LOGGER.info("Replay finished: {} of {}", done, pending.size());
        }
    }

    private static void replayTrade(Connection source, Connection target, String tradeId) throws SQLException {
        copy(source, target, "player",
                "uuid IN (SELECT player_uuid FROM trade_participant WHERE trade_id = ?)", tradeId);
        // The names seen during the fallback, which the history needs to show the name of the time,
        // and the current one: INSERT IGNORE on player keeps MariaDB's older name otherwise.
        copy(source, target, "player_name_history",
                "player_uuid IN (SELECT player_uuid FROM trade_participant WHERE trade_id = ?)", tradeId);
        copyCurrentNames(source, target, tradeId);
        copy(source, target, "item",
                "identifier IN (SELECT item_id FROM trade_item WHERE trade_id = ?)", tradeId);
        copy(source, target, "item",
                "identifier IN (SELECT held_item_id FROM trade_pokemon WHERE trade_id = ?"
                        + " AND held_item_id IS NOT NULL)", tradeId);
        copy(source, target, "species",
                "identifier IN (SELECT species_id FROM trade_pokemon WHERE trade_id = ?)", tradeId);

        copy(source, target, "trade", "id = ?", tradeId);
        copy(source, target, "trade_participant", "trade_id = ?", tradeId);
        copy(source, target, "trade_item", "trade_id = ?", tradeId);
        copy(source, target, "trade_item_components",
                "trade_item_id IN (SELECT id FROM trade_item WHERE trade_id = ?)", tradeId);
        copy(source, target, "trade_pokemon", "trade_id = ?", tradeId);
        for (String child : List.of("trade_pokemon_stat", "trade_pokemon_move",
                "trade_pokemon_aspect", "trade_pokemon_snapshot")) {
            copy(source, target, child,
                    "trade_pokemon_id IN (SELECT id FROM trade_pokemon WHERE trade_id = ?)", tradeId);
        }
        copy(source, target, "trade_money", "trade_id = ?", tradeId);
    }

    private static void replayBlacklistItem(Connection source, Connection target, String ruleId)
            throws SQLException {
        copy(source, target, "item",
                "identifier IN (SELECT item_id FROM blacklist_item WHERE id = ?)", ruleId);
        copy(source, target, "blacklist_item", "id = ?", ruleId);
    }

    private static void replayBlacklistPokemon(Connection source, Connection target, String ruleId)
            throws SQLException {
        copy(source, target, "species",
                "identifier IN (SELECT species_id FROM blacklist_pokemon WHERE id = ?)", ruleId);
        copy(source, target, "blacklist_pokemon", "id = ?", ruleId);
        copy(source, target, "blacklist_pokemon_aspect", "blacklist_id = ?", ruleId);
    }

    /**
     * Replay runs in fallback order, so SQLite's current name for a player of this trade is at
     * least as recent as the trade itself.
     */
    private static void copyCurrentNames(Connection source, Connection target, String tradeId)
            throws SQLException {
        try (PreparedStatement select = source.prepareStatement(
                "SELECT uuid, current_name FROM player WHERE uuid IN"
                        + " (SELECT player_uuid FROM trade_participant WHERE trade_id = ?)");
             PreparedStatement update = target.prepareStatement(
                     "UPDATE player SET current_name = ? WHERE uuid = ?")) {
            select.setString(1, tradeId);
            try (ResultSet rows = select.executeQuery()) {
                while (rows.next()) {
                    update.setString(1, rows.getString(2));
                    update.setString(2, rows.getString(1));
                    update.executeUpdate();
                }
            }
        }
    }

    /**
     * Keeps a copy of MariaDB's active blacklist in the local SQLite file.
     *
     * Replay only goes from SQLite to MariaDB, so a server that started with MariaDB down used to
     * find on SQLite only the rules born in some earlier fallback. Called on every read from MariaDB,
     * this makes the local copy as recent as the last time MariaDB answered. Revocations are carried
     * too, except for rules still waiting in the replay queue: those were born here and MariaDB has
     * simply not received them yet.
     */
    public static void mirrorBlacklist(Connection primary, Path sqliteFile) throws SQLException {
        if (sqliteFile == null) return;
        try (Connection local = DriverManager.getConnection("jdbc:sqlite:" + sqliteFile)) {
            Schema.applyTo(local, Dialect.SQLITE);
            local.setAutoCommit(false);
            try {
                copy(primary, local, Dialect.SQLITE, "item",
                        "identifier IN (SELECT item_id FROM blacklist_item WHERE revoked_at IS NULL)", null);
                copy(primary, local, Dialect.SQLITE, "species",
                        "identifier IN (SELECT species_id FROM blacklist_pokemon WHERE revoked_at IS NULL)", null);
                copy(primary, local, Dialect.SQLITE, "blacklist_item", "revoked_at IS NULL", null);
                copy(primary, local, Dialect.SQLITE, "blacklist_pokemon", "revoked_at IS NULL", null);
                copy(primary, local, Dialect.SQLITE, "blacklist_pokemon_aspect",
                        "blacklist_id IN (SELECT id FROM blacklist_pokemon WHERE revoked_at IS NULL)", null);
                revokeMissing(primary, local, "blacklist_item", "BLACKLIST_ITEM");
                revokeMissing(primary, local, "blacklist_pokemon", "BLACKLIST_POKEMON");
                local.commit();
            } catch (SQLException | RuntimeException e) {
                local.rollback();
                throw e;
            }
        }
    }

    private static void revokeMissing(Connection primary, Connection local, String table, String kind)
            throws SQLException {
        java.util.Set<String> active = new java.util.HashSet<>();
        try (PreparedStatement select = primary.prepareStatement(
                "SELECT id FROM " + table + " WHERE revoked_at IS NULL");
             ResultSet rows = select.executeQuery()) {
            while (rows.next()) active.add(rows.getString(1));
        }
        List<String> stale = new ArrayList<>();
        try (PreparedStatement select = local.prepareStatement(
                "SELECT id FROM " + table + " WHERE revoked_at IS NULL AND id NOT IN"
                        + " (SELECT entity_id FROM replay_pending WHERE kind = ?)")) {
            select.setString(1, kind);
            try (ResultSet rows = select.executeQuery()) {
                while (rows.next()) {
                    if (!active.contains(rows.getString(1))) stale.add(rows.getString(1));
                }
            }
        }
        if (stale.isEmpty()) return;
        try (PreparedStatement update = local.prepareStatement(
                "UPDATE " + table + " SET revoked_at = ? WHERE id = ?")) {
            for (String id : stale) {
                update.setLong(1, System.currentTimeMillis());
                update.setString(2, id);
                update.executeUpdate();
            }
        }
    }

    private static void copy(Connection source, Connection target, String table, String where,
                             String parameter) throws SQLException {
        copy(source, target, Dialect.MARIADB, table, where, parameter);
    }

    /** Copies rows between two backends without knowing their columns: it asks the ResultSet. */
    private static void copy(Connection source, Connection target, Dialect targetDialect, String table,
                             String where, String parameter) throws SQLException {
        try (PreparedStatement select = source.prepareStatement(
                "SELECT * FROM " + table + " WHERE " + where)) {
            if (parameter != null) select.setString(1, parameter);
            try (ResultSet rows = select.executeQuery()) {
                ResultSetMetaData meta = rows.getMetaData();
                int columns = meta.getColumnCount();
                String names = String.join(", ", columnNames(meta));
                String placeholders = String.join(", ", java.util.Collections.nCopies(columns, "?"));
                String insert = targetDialect.insertIgnorePrefix()
                        + table + " (" + names + ") VALUES (" + placeholders + ")";

                try (PreparedStatement write = target.prepareStatement(insert)) {
                    int batched = 0;
                    while (rows.next()) {
                        for (int column = 1; column <= columns; column++) {
                            write.setObject(column, rows.getObject(column));
                        }
                        write.addBatch();
                        batched++;
                    }
                    if (batched > 0) write.executeBatch();
                }
            }
        }
    }

    private static List<String> columnNames(ResultSetMetaData meta) throws SQLException {
        List<String> names = new ArrayList<>(meta.getColumnCount());
        for (int column = 1; column <= meta.getColumnCount(); column++) {
            names.add(meta.getColumnName(column));
        }
        return names;
    }

    private static List<Pending> pending(Connection source) throws SQLException {
        List<Pending> pending = new ArrayList<>();
        try (PreparedStatement select = source.prepareStatement(
                "SELECT kind, entity_id FROM replay_pending ORDER BY created_at");
             ResultSet rows = select.executeQuery()) {
            while (rows.next()) pending.add(new Pending(rows.getString(1), rows.getString(2)));
        }
        return pending;
    }

    private static void forget(Connection source, Pending entry) throws SQLException {
        try (PreparedStatement delete = source.prepareStatement(
                "DELETE FROM replay_pending WHERE kind = ? AND entity_id = ?")) {
            delete.setString(1, entry.kind());
            delete.setString(2, entry.entityId());
            delete.executeUpdate();
        }
    }
}
