package com.bettertrades.db;

import java.security.SecureRandom;
import java.util.concurrent.ThreadLocalRandom;

/**
 * Primary keys generated by the mod, never by the database: that is what lets the replay from the
 * SQLite fallback run without collisions. 26 Crockford base32 characters, the first 10 derived
 * from the timestamp, so they sort by creation time.
 */
public final class Ulid {

    private static final char[] ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ".toCharArray();
    private static final SecureRandom SEED = new SecureRandom();

    private Ulid() {}

    public static String next() {
        long time = System.currentTimeMillis();
        long high = ThreadLocalRandom.current().nextLong();
        long low = SEED.nextLong();

        char[] out = new char[26];
        for (int i = 9; i >= 0; i--) {
            out[i] = ALPHABET[(int) (time & 0x1F)];
            time >>>= 5;
        }
        for (int i = 25; i >= 18; i--) {
            out[i] = ALPHABET[(int) (low & 0x1F)];
            low >>>= 5;
        }
        for (int i = 17; i >= 10; i--) {
            out[i] = ALPHABET[(int) (high & 0x1F)];
            high >>>= 5;
        }
        return new String(out);
    }
}
